spring:
  datasource:
    datacore:
      jdbc-url: jdbc:mysql://192.168.0.110:3306/SdcSoft_Core_DB?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: tomcat
      password: 80201288@qq.com
