eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.110:8761/eureka
    fetch-registry: false
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.156
spring:
  application:
    name: lan-api
  profiles:
    active: prod
server:
  port: 8081