spring:
  datasource:
    datacore:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.0.110:3306/SdcSoft_Core_DB?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&&useSSL=false&useAffectedRows=true
      username: tomcat
      password: 80201288@qq.com
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #http://192.168.0.110:8761/eureka
    fetch-registry: false
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
server:
  port: 8088